services:
  - type: web
    name: chameleon-llm-demo
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATA_ROOT
        value: /app/data
      - key: OUTPUT_ROOT
        value: /app/results
    healthCheckPath: /
    autoDeploy: true
